"""Generate the isolated signer image while its full certificate is developed."""
from pathlib import Path
from build import build

if __name__ == '__main__':
    words = build('sign', derive_pk=True)
    original = build('sign')
    assert len(words) == 847 and len(original) == 796
    assert words[1:len(original)] == original[1:]
    lines = ['-- Generated by examples/hypertree/build_prelude.py.',
             'import SigGolfCandidate.Hypertree.Images', '',
             'namespace SigGolfCandidate.Hypertree',
             'def signPrelude : SigGolf.Riscv.Image where', '  code := [']
    for i in range(0, len(words), 8):
        lines.append('    ' + ', '.join(f'0x{w:08x}' for w in words[i:i+8]) +
                     (',' if i + 8 < len(words) else ']'))
    lines += ['  data := []', 'end SigGolfCandidate.Hypertree', '']
    (Path(__file__).resolve().parents[2] / 'SigGolfCandidate/Hypertree/ImagesPrelude.lean').write_text('\n'.join(lines))
